#! /bin/bash
# Convert and run one configuration
# Args: <product>-<variant>
[[ $# -eq 1 && "$1" =~ ^(.*)-(.*)$ ]] || { echo Usage: ${0##*/} PRODUCT-VARIANT >&2; exit 1; }
declare -r product="${BASH_REMATCH[1]:-aosp_arm}"
declare -r variant="${BASH_REMATCH[2]:-eng}"
set -eu
declare -r output_root=${OUT_DIR:-out}
declare -r runner="$output_root/soong/.bootstrap/bin/rbcrun"
declare -r converter="$output_root/soong/.bootstrap/bin/mk2rbc"
declare -r launcher=$output_root/launchers/run.rbc
$converter -mode=write -r --outdir $output_root --launcher=$launcher $product
printf "#TARGET_PRODUCT=$product TARGET_BUILD_VARIANT=$variant\n"
env TARGET_PRODUCT=$product TARGET_BUILD_VARIANT=$variant \
  $runner RBC_OUT="make,global" RBC_DEBUG="${RBC_DEBUG:-}" $launcher

